version: 2
jobs:
    build:
        machine:
            #image: circleci/classic:201708-01 # VM will run Ubuntu 14.04 for this release date
            image: ubuntu-1604:201903-01
            enabled: true
        steps:
            - checkout:
            - run:
                name: Clone Git Submodules
                command: |
                    git submodule init
                    git submodule update
                    cd dependency/IFL
                    git checkout master
                    git remote update
                    git pull origin master
                    git log -n 1 --pretty=oneline
            - run: 
                name: Build ILFForTLS
                command: make

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
