version: 2
jobs:
    build:
        machine:
            enabled: true
        steps:
            - checkout:
            - run:
                name: Clone Git Submodules
                command: |
                    git submodule init
                    git submodule update
                    git log -n 1 --pretty=oneline
            - run: 
                name: Build ILFForTLS
                command: make

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
