version: 2
jobs:
    build:
        machine:
            enabled: true
        steps:
            - checkout
            - run: 
                name: Build ILF
                command: make

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
